name: Selective Deployment to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'  # Monitor changes in the 'data' folder at the root
      - 'docs/**'  # Monitor changes in the 'docs' folder at the root

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Deploy to the 'main' branch
          folder: .
